services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootSecurePassword123
      MYSQL_DATABASE: task-management
      MYSQL_USER: appuser
      MYSQL_PASSWORD: mySecurePassword123
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-prootSecurePassword123",
        ]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_NAME=task-management
      - DB_USER=appuser
      - DB_PASSWORD=mySecurePassword123
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
